{% set name = "pytkdocs" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: 5d5ebf316ed9b32f3b85270a9d58f478978ab4fbb472fd0f3550cd925a220f1d

build:
  number: 0
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - pdm
  run:
    - python
    - astunparse >=1.6,<1.7  # [py<39]
    - dataclasses >=0.7,<0.9  # [py<37]
    - typing_extensions >=3.7,<3.8  # [py<38]
    - cached-property >=1.5,<1.6  # [py<38]
    - docstring_parser >=0.7,<0.8

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
    - pytkdocs.loader
    - pytkdocs.objects
    - pytkdocs.cli
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/pytkdocs
  doc_url: https://mkdocstrings.github.io/pytkdocs/
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
