{% set name = "pytkdocs" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: c773241b1281a390a788ba8d3533f7d558634a9f05924088a0a85494fb633418

build:
  number: 0
  noarch: python
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
    - dataclasses >=0.7
    - typing-extensions >=3.7.4.3
  run:
    - python >=3.6,<4.0

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/pawamoy/pytkdocs
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
