{% set name = "pytkdocs" %}
{% set version = "0.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: e2ccf6dfe9dbbceb09818673f040f1a7c32ed0bffb2d709b06be6453c4026045

build:
  noarch: python
  number: 0
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - python >=3.7
    - astunparse >=1.6
    - cached-property >=1.5
    - typing_extensions >=3.7
    - docstring_parser >=0.7

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
    - pytkdocs.loader
    - pytkdocs.objects
    - pytkdocs.cli
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/pytkdocs
  doc_url: https://mkdocstrings.github.io/pytkdocs/
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - cpcloud
