{% set name = "pytkdocs" %}
{% set version = "0.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: b3420ffefeb8892f4498dd8ad6ecca867f7cab1b7741057ac92f30bfe2ccdb4d

build:
  number: 0
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - pdm
  run:
    - python
    - astunparse >=1.6  # [py<39]
    - cached-property >=1.5  # [py<38]
    - dataclasses >=0.7,<0.9  # [py<37]
    - typing_extensions >=3.7  # [py<38]
    - docstring_parser >=0.7

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
    - pytkdocs.loader
    - pytkdocs.objects
    - pytkdocs.cli
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/pytkdocs
  doc_url: https://mkdocstrings.github.io/pytkdocs/
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
