{% set name = "pytkdocs" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: f3d510063e7c2951c7b52cc860846ecbd7b21ec4b2253ae5c0084a26b233132f

build:
  number: 0
  noarch: python
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
    - dataclasses >=0.7
    - typing-extensions >=3.7.4.3
  run:
    - python >=3.6,<4.0

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/pawamoy/pytkdocs
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
